version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data:/data
    restart: unless-stopped
    networks:
      - selfhost
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    pid: host
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w -t 10"
    networks:
      - selfhost
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptimekuma
    restart: unless-stopped
    volumes:
      - uptime-kuma:/app/data
    expose:
      - 3001
    networks:
      - selfhost
  doku:
    image: amerkurev/doku:latest
    container_name: doku
    restart: unless-stopped
    networks:
      - selfhost
    expose:
      - 9090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/hostroot:ro
  fail2ban:
    image: lscr.io/linuxserver/fail2ban:1.0.2
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    environment:
      - PUID=911
      - PGID=911
      - TZ=Etc/UTC
      - VERBOSITY=-vv
    volumes:
      - ./config/fail2ban:/config/fail2ban
      - /etc/localtime:/etc/localtime:ro
      - /var/log:/var/log:ro
      - authelia_logs:/remotelogs/authelia:ro
    restart: unless-stopped

volumes:
  data:
  uptime-kuma:
  authelia_logs:
    external:
      name: iam_authelia_logs

networks:
  selfhost:
    external: true
